In [2]:
import torch

In [10]:
a = torch.tensor([[1,2,3]], dtype=torch.float32)
print(a.shape)
print(a.dtype)
a

torch.Size([1, 3])
torch.float32


tensor([[1., 2., 3.]])

In [17]:
b = torch.rand((3,3,3),dtype=torch.float32)
b

tensor([[[0.2909, 0.1677, 0.9304],
         [0.8519, 0.0230, 0.0180],
         [0.6912, 0.4446, 0.4666]],

        [[0.6233, 0.6828, 0.6163],
         [0.4338, 0.1162, 0.6249],
         [0.6385, 0.8740, 0.9119]],

        [[0.8756, 0.9253, 0.7969],
         [0.7438, 0.7294, 0.0311],
         [0.1094, 0.1664, 0.3130]]])

In [24]:
a = torch.arange(10)
b = torch.ones(10)

print(f"{a = }")
print(f"{b = }")

print(f"{a+b = }")

print(f"{a*b = }")

print(f"{a-b = }")


print(f"{a**(2*b) = }")

a = tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
a+b = tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
a*b = tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
a-b = tensor([-1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])
a**(2*b) = tensor([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])


In [25]:
a = torch.rand(4)
b = torch.rand(5)

##cant do a + b bc dims are different (except broadcasting which we cover later)


In [27]:
####COOOL way to write long numbers!!!
a = torch.rand(1_000_000_000)
b = torch.rand(1_000_000_000)

c = a + b


In [28]:
%timeit c= a + b

The slowest run took 9.70 times longer than the fastest. This could mean that an intermediate result is being cached.
4.42 s ± 3.95 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
a_gpu = a.to('cuda')
b_gpu = b.to("cuda")


%timeit c_gpu = a_gpu + b_gpu


In [ ]:
a = torch.arange(6)

#view and reshape are ways to maniupluate shape
#view doesn't copy underlying data, reshape does
print(a.view(2,3))

tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
a = torch.rand(2,3)
print(a)
#matrix transpose
print(a.mT)

tensor([[0.5239, 0.9276, 0.3205],
        [0.4846, 0.7780, 0.8990]])
tensor([[0.5239, 0.4846],
        [0.9276, 0.7780],
        [0.3205, 0.8990]])


In [39]:
a = torch.rand(2,3,4)
print(a.permute(1,2,0).shape)

torch.Size([3, 4, 2])


In [46]:
a = torch.arange(6).view(3,2)

#creates a singleton dim whereever you put None
print(a[None].shape)
print(a[:,None].shape)
print(a[None, :,None].shape)

#just add dim to end 
print(a[...,None].shape)

torch.Size([1, 3, 2])
torch.Size([3, 1, 2])
torch.Size([1, 3, 1, 2])
torch.Size([3, 2, 1])


In [51]:
a = torch.arange(6).view(3,2,1,1)
#ways to remove last dim
print(a[...,0].shape)
#squeeze removes dims that are size one  so this works
print(a.squeeze(-1).shape)
#but this does nothing
print(a.squeeze(0).shape)

#NEVER do this, but this gets rid of all dims of size one
print(a.squeeze().shape)

torch.Size([3, 2, 1])
torch.Size([3, 2, 1])
torch.Size([3, 2, 1, 1])
torch.Size([3, 2])


In [ ]:
a = torch.arange(4)
b = torch.arange(5)

try:
    print(a + b)
except:
    print('This fails')

#if dim is 1 then it works. Just adds scalar everywhere
a = torch.arange(1)
b = torch.arange(5)

try:
    print(a + b)
except:
    print('This fails')

#why does this work?
#broadcasting
#duplicates a along 2nd dim (the size 1) and b along 1st
a = torch.rand((4,1))
b = torch.rand((1,5))

try:
    print(a + b)
    print((a+b).shape)
except:
    print('This fails')

This fails
tensor([0, 1, 2, 3, 4])
tensor([[1.1903, 1.2113, 0.8792, 0.8774, 1.2966],
        [0.9576, 0.9786, 0.6465, 0.6447, 1.0639],
        [1.8094, 1.8304, 1.4983, 1.4965, 1.9157],
        [1.4061, 1.4272, 1.0950, 1.0932, 1.5124]])
torch.Size([4, 5])


In [59]:
a = torch.arange(4).view(4,1)
b = torch.arange(5).view(1,5)*10

print(f'{a = }')
print(f'{b = }')
print(f'{a + b = }')
print(f'{a * b = } Note that this is outer product')

a = tensor([[0],
        [1],
        [2],
        [3]])
b = tensor([[ 0, 10, 20, 30, 40]])
a + b = tensor([[ 0, 10, 20, 30, 40],
        [ 1, 11, 21, 31, 41],
        [ 2, 12, 22, 32, 42],
        [ 3, 13, 23, 33, 43]])
a * b = tensor([[  0,   0,   0,   0,   0],
        [  0,  10,  20,  30,  40],
        [  0,  20,  40,  60,  80],
        [  0,  30,  60,  90, 120]]) Note that this is outer product


In [65]:
#how to do elementwise distance of all elements without broadcasting??

x = torch.randn(10,2)
d = torch.zeros(10,10)

for i in range(10):
    for j in range(10):
        d[i,j] = (x[i] - x[j]).pow(2).sum()

print(d.sum())

#with broadcasting
#add singleton in 2nd dim and subtract by one with singleton in 1st. 
#subtracts any row in x from any other row
# so it gives d[i,j] = x[i] - x[j] for every i, j
d = (x[:, None, :] - x[None,:,:]).pow(2).sum()
print(d)

tensor(579.1530)
tensor(579.1531)


In [72]:
#what about max distance? 
d = (x[:, None, :] - x[None,:,:]).pow(2)
print(d.max(), (d.argmax()//d.shape[0], d.argmax()%d.shape[0]))

#argmax flattens first, so to get point use floor to get row and mod to get column

tensor(18.5897) (tensor(1), tensor(5))


In [74]:
a = torch.rand(2,4)
b = torch.rand(4,3)
# mat mul
c = a @ b
print(c.shape)

torch.Size([2, 3])
