In [1]:
import torch

In [ ]:
def make_it_pytorch_7(x: torch.Tensor) -> torch.Tensor:
        """
        Return the diagonal elements (top right to bottom left) of the input tensor

        x is a 2D tensor

        --------
        y = []
        for i in range(min(x.shape[0], x.shape[1])):
            y.append(x[i, x.shape[1] - i - 1])
        return torch.as_tensor(y)
        --------

        Solution length: 27 characters
        """
        return torch.diagonal(torch.flip(x,[1]))

In [37]:
a = torch.arange(8).view(2,4)
a

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [38]:
make_it_pytorch_7(a)

tensor([3, 6])

In [39]:
def make_it_pytorch_7_slow(x: torch.Tensor) -> torch.Tensor:

        y = []
        for i in range(min(x.shape[0], x.shape[1])):
            y.append(x[i, x.shape[1] - i - 1])
        return torch.as_tensor(y)

In [40]:
make_it_pytorch_7_slow(a)

tensor([3, 6])

In [ ]:
def make_it_pytorch_3_slow(x: torch.Tensor) -> torch.Tensor:
        """
        Return the unique elements of the input tensor in sorted order

        x can have any dimension

        """
        y = []
        for i in x.flatten():
            if i not in y:
                y.append(i)
        return torch.as_tensor(sorted(y))

def make_it_pytorch_3(x: torch.Tensor) -> torch.Tensor:
        """
        Return the unique elements of the input tensor in sorted order

        x can have any dimension

        --------
        y = []
        for i in x.flatten():
            if i not in y:
                y.append(i)
        return torch.as_tensor(sorted(y))
        --------

        Solution length: 22 characters
        """
        return torch.unique(x)

def make_it_pytorch_8_slow(x: torch.Tensor) -> torch.Tensor:
        """
        Return the cumulative sum of the input tensor

        x is a 1D tensor
        """
        if len(x) == 0:
            return torch.as_tensor(x)
        y = [x[0]]
        for i in range(1, len(x)):
            y.append(y[i - 1] + x[i])
        return torch.as_tensor(y)

In [44]:
g = torch.Generator().manual_seed(2147483647)
cases = [(torch.randn(n // 2, n, n + 4, generator=g) * 5).int() for n in range(4, 20)]

for i in cases:
    print(make_it_pytorch_3_slow(i) == make_it_pytorch_3(i))


tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True])
tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True])
tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True])
tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True])
tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True])
tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True])
tensor([True, True, Tr

In [45]:
a = torch.arange(10)
print(a)
print(torch.cumsum(a,0))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])


In [46]:
x = torch.arange(8).view(4,2)
print(x)

c = torch.tensor([5])
print(c)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])
tensor([5])


In [49]:
torch.where(x>c.item(), x, 0)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [6, 7]])

In [51]:
x = torch.arange(27).view(3,3,3)
print(x)


tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])


In [53]:
torch.max(x, dim=-1).values

tensor([[ 2,  5,  8],
        [11, 14, 17],
        [20, 23, 26]])

In [61]:
x = torch.arange(16, dtype = torch.float32).view(2,8)
print(x)
print(torch.mean(x, dim = 0))

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]])
tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [62]:
x = torch.arange(10)

x[::3]

tensor([0, 3, 6, 9])

In [2]:
def nine(x):
    y = torch.zeros_like(x)
    for i in range(0, x.shape[0]):
        for j in range(0, x.shape[1]):
            y[i, j] = x[i, j]
            if i > 0:
                y[i, j] += y[i - 1, j]
            if j > 0:
                y[i, j] += y[i, j - 1]
            if i > 0 and j > 0:
                y[i, j] -= y[i - 1, j - 1]
    return y

x = torch.arange(9).view(3,3)
print(x)
nine(x)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor([[ 0,  1,  3],
        [ 3,  8, 15],
        [ 9, 21, 36]])

In [6]:
print(torch.cumsum(x, dim = 0))
print(torch.cumsum(x, dim = 1))
print(torch.cumsum(x, dim = 0) + torch.cumsum(x, dim = 1) )
print(torch.cumsum(torch.cumsum(x,dim = 0),dim=1))

tensor([[ 0,  1,  2],
        [ 3,  5,  7],
        [ 9, 12, 15]])
tensor([[ 0,  1,  3],
        [ 3,  7, 12],
        [ 6, 13, 21]])
tensor([[ 0,  2,  5],
        [ 6, 12, 19],
        [15, 25, 36]])
tensor([[ 0,  1,  3],
        [ 3,  8, 15],
        [ 9, 21, 36]])


In [70]:
def e1(x,y):
    xy = []
    for xi in x:
        xy.append(xi)
    for yi in y:
        xy.append(yi)

    z = []
    for xy1, xy2 in zip(xy[1:], xy[:-1]):
        z.append(xy1 - xy2)
    return torch.as_tensor(z)

x = torch.arange(10)
y = torch.arange(start = 10, end = 0, step = -1)
print(x)
print(y)
print(e1(x,y))

print(torch.diff(torch.cat((x,y))))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])
tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1])
tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1])


In [ ]:
x = torch.arange(10)
y = torch.arange(start = 10, end = 0, step = -1)

x_t = x[:,None]
y_t = y[None, :]
print(x_t)
print(y_t)
x_t = x[:,None]
y_t = y[None, :]
#torch.where(torch.abs(x_t-y_t)<1e-3,1,0).sum()


tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
tensor([[10,  9,  8,  7,  6,  5,  4,  3,  2,  1]])


tensor([[False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False,  True],
        [False, False, False, False, False, False, False, False,  True, False],
        [False, False, False, False, False, False, False,  True, False, False],
        [False, False, False, False, False, False,  True, False, False, False],
        [False, False, False, False, False,  True, False, False, False, False],
        [False, False, False, False,  True, False, False, False, False, False],
        [False, False, False,  True, False, False, False, False, False, False],
        [False, False,  True, False, False, False, False, False, False, False],
        [False,  True, False, False, False, False, False, False, False, False]])

In [74]:
def e2(x,y):
    count = 0
    for xi in x:
        for yi in y:
            if abs(xi - yi) < 1e-3:
                count += 1
                break
    return torch.as_tensor(count)

e2(x,y)

tensor(9)

In [85]:
def eleven(x,c):
    row, col = [], []
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            if x[i, j] < c:
                row.append(i)
                col.append(j)
    return torch.as_tensor([row, col])

x = torch.arange(10).view(5,2)
c = torch.as_tensor(4)
print(x)
print(c)
print(eleven(x, c))

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor(4)
tensor([[0, 0, 1, 1],
        [0, 1, 0, 1]])


In [93]:
temp = torch.where(x<c)
torch.stack((temp[0], temp[1]))

tensor([[0, 0, 1, 1],
        [0, 1, 0, 1]])

In [ ]:
x = torch.tensor([[0.0, 0.0], [0.0, 0.0]])
print(torch.mean(x, dim = 0, keepdim=True))
print(torch.std(x, dim= 0).shape)

tensor([0., 0.])
torch.Size([2])


In [ ]:
inputs = [
            (
                torch.FloatTensor([[2.0, -1.0], [0.0, 1.0], [-3.0, 2.0], [0.0, 2.0]]),
                torch.FloatTensor([1.0, 0.0, 1.0, 1.0]),
                torch.FloatTensor([[1.0, -1.0]]),
            ),
            (
                torch.FloatTensor([[-1.0], [-3.0], [0.0], [-2.0], [-1.0]]),
                torch.FloatTensor([1.0, 1.0, 1.0, 0.0, 1.0]),
                torch.FloatTensor([[1.0]]),
            ),
        ]


tensor([[ 2., -1.],
        [ 0.,  1.],
        [-3.,  2.],
        [ 0.,  2.]])

In [133]:
data_raw = torch.FloatTensor(
                [
                    [84.0, 95.7, 69.8, 93.7, 70.9, 77.6, 97.6, 51.8, 59.2, 68.6],
                    [65.2, 96.6, 58.7, 63.4, 57.5, 51.5, 60.4, 96.4, 86.1, 87.1],
                    [76.3, 62.1, 79.2, 51.6, 56.9, 62.1, 90.7, 89.6, 63.9, 74.0],
                    [90.9, 99.8, 84.9, 78.3, 91.7, 60.2, 79.6, 55.6, 57.6, 62.0],
                    [86.3, 85.0, 60.1, 82.5, 88.7, 71.8, 75.9, 80.7, 90.5, 99.0],
                    [55.7, 65.8, 84.8, 95.7, 96.7, 97.0, 79.9, 53.2, 77.2, 59.3],
                    [51.7, 97.2, 94.0, 50.0, 79.6, 70.7, 70.8, 63.5, 84.6, 60.1],
                    [84.1, 87.6, 92.8, 84.3, 50.2, 58.7, 87.4, 80.2, 55.4, 60.6],
                    [98.5, 91.8, 64.0, 68.7, 51.1, 74.5, 56.1, 55.7, 73.6, 78.7],
                    [64.7, 89.8, 59.7, 97.6, 92.1, 53.9, 68.7, 76.1, 78.6, 80.9],
                    [84.8, 76.4, 62.8, 86.8, 51.0, 60.1, 68.7, 62.8, 66.2, 54.5],
                    [69.6, 80.3, 58.7, 73.7, 92.8, 72.4, 75.6, 72.8, 80.0, 90.8],
                    [98.6, 90.8, 98.7, 73.1, 52.5, 63.1, 92.0, 74.8, 62.5, 55.8],
                    [51.6, 53.8, 69.9, 88.7, 88.5, 50.8, 90.5, 55.4, 69.7, 64.8],
                    [70.1, 70.0, 52.5, 53.4, 71.0, 75.3, 63.6, 84.4, 52.4, 73.3],
                    [96.9, 64.8, 97.5, 84.0, 52.4, 90.8, 72.1, 63.8, 94.9, 54.7],
                    [77.6, 69.7, 92.8, 81.9, 87.0, 83.8, 68.9, 69.7, 54.3, 88.5],
                    [94.8, 92.1, 57.3, 76.1, 57.3, 61.2, 60.4, 83.5, 60.1, 74.4],
                    [76.0, 91.1, 56.1, 57.8, 60.4, 92.4, 66.0, 96.0, 84.0, 78.1],
                    [74.8, 70.0, 78.1, 69.2, 74.8, 78.1, 55.4, 61.8, 95.1, 54.7],
                    [73.2, 99.7, 84.0, 75.7, 53.3, 87.3, 57.1, 67.9, 66.6, 71.2],
                    [75.2, 95.6, 78.1, 97.3, 90.2, 59.1, 86.2, 57.3, 64.4, 82.3],
                    [83.2, 93.7, 66.9, 75.0, 87.8, 50.8, 93.0, 54.3, 75.3, 70.7],
                    [61.8, 78.3, 95.6, 67.6, 60.1, 65.7, 50.2, 86.2, 62.9, 58.3],
                    [60.5, 89.3, 88.2, 94.1, 84.0, 66.6, 68.0, 82.3, 95.5, 81.7],
                    [63.1, 63.2, 51.3, 80.4, 60.9, 52.7, 96.9, 58.7, 72.1, 82.1],
                    [75.7, 58.1, 54.7, 94.9, 79.0, 95.7, 66.6, 82.3, 69.2, 73.8],
                    [59.7, 83.4, 82.9, 74.4, 69.3, 59.5, 92.2, 56.3, 85.2, 66.5],
                    [62.9, 79.4, 62.0, 80.7, 79.9, 56.4, 79.1, 85.6, 84.8, 71.8],
                    [54.5, 71.1, 83.6, 65.8, 84.4, 91.6, 61.9, 75.2, 85.3, 76.9],
                ]
            )
data = torch.as_tensor(data_raw).view(-1, 10)

In [159]:
m = torch.mean(data, dim = 1)
print(m)
torch.min(torch.diff(m))
#data[torch.max(torch.abs(data - m), dim = 1,keepdim=True).indices]

tensor([76.8900, 72.2900, 70.6400, 76.0600, 82.0500, 76.5300, 72.2200, 74.1300,
        71.2700, 76.2100, 67.4100, 76.6700, 76.1900, 68.3700, 66.6000, 77.1900,
        77.4200, 71.7200, 75.7900, 71.2000, 73.6000, 78.5700, 75.0700, 68.6700,
        81.0200, 68.1400, 75.0000, 72.9400, 74.2600, 75.0300])


tensor(-12.8800)

In [170]:
ind = torch.max(torch.abs(data - m[:, None]), dim = 1).indices
print(torch.max(torch.abs(data - m[:, None]), dim = 1))

torch.return_types.max(
values=tensor([25.0900, 24.3100, 20.0600, 23.7400, 21.9500, 23.3300, 24.9800, 23.9300,
        27.2300, 22.3100, 19.3900, 17.9700, 23.6900, 22.1300, 17.8000, 24.7900,
        23.1200, 23.0800, 20.2100, 23.9000, 26.1000, 21.2700, 24.2700, 26.9300,
        20.5200, 28.7600, 20.7000, 19.2600, 17.8600, 20.5300]),
indices=tensor([7, 1, 6, 1, 2, 7, 1, 4, 0, 5, 3, 2, 4, 6, 7, 4, 8, 0, 7, 8, 1, 7, 5, 2,
        0, 6, 5, 6, 5, 0]))


In [172]:
vals  = data[torch.arange(data.size(0)), ind]
vals

tensor([51.8000, 96.6000, 90.7000, 99.8000, 60.1000, 53.2000, 97.2000, 50.2000,
        98.5000, 53.9000, 86.8000, 58.7000, 52.5000, 90.5000, 84.4000, 52.4000,
        54.3000, 94.8000, 96.0000, 95.1000, 99.7000, 57.3000, 50.8000, 95.6000,
        60.5000, 96.9000, 95.7000, 92.2000, 56.4000, 54.5000])

In [173]:
data

tensor([[84.0000, 95.7000, 69.8000, 93.7000, 70.9000, 77.6000, 97.6000, 51.8000,
         59.2000, 68.6000],
        [65.2000, 96.6000, 58.7000, 63.4000, 57.5000, 51.5000, 60.4000, 96.4000,
         86.1000, 87.1000],
        [76.3000, 62.1000, 79.2000, 51.6000, 56.9000, 62.1000, 90.7000, 89.6000,
         63.9000, 74.0000],
        [90.9000, 99.8000, 84.9000, 78.3000, 91.7000, 60.2000, 79.6000, 55.6000,
         57.6000, 62.0000],
        [86.3000, 85.0000, 60.1000, 82.5000, 88.7000, 71.8000, 75.9000, 80.7000,
         90.5000, 99.0000],
        [55.7000, 65.8000, 84.8000, 95.7000, 96.7000, 97.0000, 79.9000, 53.2000,
         77.2000, 59.3000],
        [51.7000, 97.2000, 94.0000, 50.0000, 79.6000, 70.7000, 70.8000, 63.5000,
         84.6000, 60.1000],
        [84.1000, 87.6000, 92.8000, 84.3000, 50.2000, 58.7000, 87.4000, 80.2000,
         55.4000, 60.6000],
        [98.5000, 91.8000, 64.0000, 68.7000, 51.1000, 74.5000, 56.1000, 55.7000,
         73.6000, 78.7000],
        [64.7000, 8

In [178]:
k  =10
torch.max(data, dim = 1).values[-k:]

tensor([99.7000, 97.3000, 93.7000, 95.6000, 95.5000, 96.9000, 95.7000, 92.2000,
        85.6000, 91.6000])

In [188]:
unknown = torch.FloatTensor([74.8, 88.4, 54.4, 56.6, 65.3, 81.7, 74.5, 94.8, 72.7, 81.6])
print(torch.argmin(torch.abs(data-unknown).sum(dim = 1)))

tensor(18)
