In [1]:
import torch
import torch.nn as nn

In [4]:
model = nn.Linear(10, 1)
model

Linear(in_features=10, out_features=1, bias=True)

In [5]:
x = torch.ones(10)
model(x)

tensor([-0.5553], grad_fn=<ViewBackward0>)

In [ ]:
class LinearClassifier(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__() ###ALWAYS DO THIS when using nn.Module  
        self.fc = torch.nn.Linear(input_dim, output_dim)
    def forward(self, x):
        ##DON'T DO THIS! DOnt put sigmoid directly in the forward
        return nn.functional.sigmoid(self.fc(x))
    

model = LinearClassifier(10, 1)
print(model.fc.weight)
x = torch.zeros(10)
print(model(x))

x = torch.ones(10)*50
model(x)

Parameter containing:
tensor([[-0.1071,  0.1856,  0.0733, -0.2525,  0.0262,  0.2943,  0.1103, -0.1516,
         -0.0120, -0.2491]], requires_grad=True)
tensor([0.4783], grad_fn=<SigmoidBackward0>)


tensor([0.0145], grad_fn=<SigmoidBackward0>)

In [15]:
class LinearClassifier(torch.nn.Module):
    def __init__(self, input_dim, n_classes):
        super().__init__() ###ALWAYS DO THIS when using nn.Module  
        self.fc = torch.nn.Linear(input_dim, n_classes)
    def forward(self, x):
        return nn.functional.softmax(self.fc(x), dim = -1)
    

model = LinearClassifier(10, 4)
x = torch.zeros(10)
print(model(x))



tensor([0.2759, 0.2593, 0.2538, 0.2110], grad_fn=<SoftmaxBackward0>)
