In [2]:
import torch

In [3]:
x = torch.rand(10, requires_grad =True)
y = torch.rand(10)
print(x)
print(y)

tensor([0.7676, 0.6473, 0.5451, 0.5891, 0.3830, 0.9547, 0.9854, 0.6771, 0.1787,
        0.7241], requires_grad=True)
tensor([0.1059, 0.6860, 0.0727, 0.1122, 0.4447, 0.8728, 0.9568, 0.8358, 0.3077,
        0.1746])


In [4]:
#has a grad fn attached
b=(x**2).mean()
print(b)
#populates x's gradient
b.backward()

tensor(0.4696, grad_fn=<MeanBackward0>)


In [5]:
print(x/10 * 2)
print(x.grad)

tensor([0.1535, 0.1295, 0.1090, 0.1178, 0.0766, 0.1909, 0.1971, 0.1354, 0.0357,
        0.1448], grad_fn=<MulBackward0>)
tensor([0.1535, 0.1295, 0.1090, 0.1178, 0.0766, 0.1909, 0.1971, 0.1354, 0.0357,
        0.1448])


In [6]:
try:
    b.backward()
except:
    print("You can't compute backward again")
    print('need to redefine b')
    print("IMPORTANT this will sum up the gradient of x!!")

#has a grad fn attached
b=(x**2).mean()
#populates x's gradient
b.backward()
print(x/10 * 2)
print(x.grad)
print('x.grad changed')

You can't compute backward again
need to redefine b
IMPORTANT this will sum up the gradient of x!!
tensor([0.1535, 0.1295, 0.1090, 0.1178, 0.0766, 0.1909, 0.1971, 0.1354, 0.0357,
        0.1448], grad_fn=<MulBackward0>)
tensor([0.3070, 0.2589, 0.2180, 0.2356, 0.1532, 0.3819, 0.3942, 0.2708, 0.0715,
        0.2896])
x.grad changed


In [7]:
torch.cuda.memory_allocated()

0

In [15]:
x = torch.randn(1000000, requires_grad = True, device = 'cuda')
torch.cuda.memory_allocated() /1024/1024 #num MB

15.259765625

In [16]:
for _ in range(10):
    b = torch.relu(x)
print(torch.cuda.memory_allocated() /1024/1024) #num MB


b.sum().backward()

torch.cuda.memory_allocated() /1024/1024

7.6298828125


12.3701171875

In [14]:
torch.cuda.memory_allocated() /1024/1024

11.44482421875